#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S4,     Gyro,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     rightmotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightslidemotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftmotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftslidemotor, tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    bucketservo,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "hitechnic-gyro.h"

float happy_angle=0;

task update_gyro ()
{
	HTGYROstartCal(Gyro);
	while(true)
	{
		float angle=HTGYROreadRot(Gyro)/100.0;
		happy_angle=happy_angle+angle;
		nxtDisplayTextLine(7, "%d", happy_angle);
		wait1Msec (10);
	}
}

task main ()
{
	waitForStart();
	StartTask (update_gyro);


	while (true)
	{
		if (happy_angle < 3 && happy_angle > -3)//while straight go straight
		{
			nxtDisplayTextLine(6, "Going Straight");
			motor[rightmotor]=50;
			motor[leftmotor]=50;
		}
		if (happy_angle>3)// while rightmotor go leftmotor
		{
			nxtDisplayTextLine(6, "Going leftmotor");
			motor[rightmotor]=35;
			motor[leftmotor]=50;
		}
		if (happy_angle<-3)// while leftmotor go rightmotor
		{
			nxtDisplayTextLine(6, "Going rightmotor");

			motor[leftmotor]=50;
			motor[rightmotor]=35;
		}
	}
}
