#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     Motorleft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Motorright,    tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>
#include <hitechnic-sensormux.h>
#include <hitechnic-irseeker-v2.h>
#include <hitechnic-gyro.h>

float happy_angle=0;

task update_gyro ()
{
	HTGYROstartCal(Gyro);
	while(true)
	{
		float angle=HTGYROreadRot(Gyro)/100.0;
		happy_angle=happy_angle+angle;
		wait1Msec (10);
	}
}

const tMUXSensor irseeker = msensor_S2_1;
const tMUXSensor lineSensor = msensor_S2_2;
const tMUXSensor touchSensor = msensor_S2_3;
const tMUXSensor gyroSensor = msensor_S2_4;


void goStraight(int time)
{
	time1[T1] = 0;
	while(time1[T1] < time)
	{
		if (happy_angle <2 &&happy_angle>-2)//while straigt go straight
		{
			nxtDisplayTextLine(6, "Going Straight");
			motor[Motorright]=100;
			motor[Motorleft]=100;
		}
		if (happy_angle>2)// while right go left
		{
			nxtDisplayTextLine(6, "Going Left");
			motor[Motorright]=50;
			motor[Motorleft]=55;
		}
		if (happy_angle<-2)// while left go right
		{
			nxtDisplayTextLine(6, "Going Right");
			motor[Motorleft]=55;
			motor[Motorright]=50;
		}
	}
}

int readIR()
{
	int IRValue = HTIRS2readACDir(irseeker);
	return IRValue;
}

//bool alignWithBeacon = false;

void followIR()
{
	if (readIR()< 5 && readIR()>0)
	{
		motor[Motorleft]=-50;
		motor[Motorright]=50;
		nxtDisplayTextLine(3,"Left");
	}
	else if (readIR()> 5)
	{
		motor[Motorleft]=50;
		motor[Motorright]=-50;
		nxtDisplayTextLine(3,"Right");
	}
	else if (readIR()== 5)
	{
		motor[Motorleft]=25;
		motor[Motorright]=25;

		nxtDisplayTextLine(3,"Forward");
	}
	else
	{
		motor[Motorleft]=0;
		motor[Motorright]=0;

		nxtDisplayTextLine(3,"Stop");
	}
}

bool isOnLine()
{
	if(SensorValue[lineSensor] > 45)
	{
		return true;
	}
	else
	{
		return false;
	}

}

bool bumperIsPressed()
{
	if(SensorValue(touchSensor) == 1)
	{
		return true;
	}
	else
	{
		return false;
	}
}

bool inLineWithGoal()
{
	if(isOnLine() == true && SensorValue[irseeker] == 4)
	{
		return true;
	}
	else
	{
		return false;
	}
}

int alignWithBeaconPole()
{

}

int driveUntilBumper(int motorSpeed)
{
	while(SensorValue[touchSensor] == false)
	{
		motor[motorLeft] = 55;
		motor[motorRight] = 55;
	}
	return SensorValue[touchSensor];
}

void driveUntilIR(int irValue, int motorSpeed)
{
	irValue = 9;

}

void turnToAngle(int motorSpeedTurn, int motorSpeedForward, int angle)
{

}

/*
	Go strait until bumper pressed
	Determine placement of IR beacon
	Read gyro x>z
	Backup turing right until gyro is less than 90
	Drive forward until IR == 8 or 9
	Turn right 90 degrees
	Lift
	drive forward
	Place scoring element
	Drive back and lower slides

*/

task main()
{
	StartTask (update_gyro);
	/*
	while(true)
	{
		//Drive Forward, while the IR receiver reads a value of 5
		//
		if(SensorValue(irseeker) == 5 && bumperIsPressed() == false)
		{
			motor[Motorright] = 35;
			motor[Motorleft] = 35;
		}
		else if(SensorValue(irseeker) == 0 && bumperIsPressed() == false)
		{
			motor[Motorright] = -5;
			motor[Motorleft] = -5;
		}
		else
		{
			motor[Motorright] = 0;
			motor[Motorleft] = 0;
		}*/
		goStraight(10000);

	//}
}
