#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightmotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftmotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightslidemotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftslidemotor, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    bucketservo,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
int joystick_to_motor (int joystick_value) //Converts the joystick value to the motor//
{																					//value using an exponetional function.//
	float motor_value;
	motor_value=(joystick_value*joystick_value/163.4);
	if (joystick_value<0)
	{
		motor_value=motor_value*-1.0;
	}
	return(motor_value);
}
const int Left = 0;
const int Right = 1;

int read_joystick(int side)
{
	int joystick_value;

	// if side is Left
	if (side == Left)
	{
		// read left joystick Y
		joystick_value = joystick.joy1_y1;
	}
	// else
	else if (side == Right)
	{
		// read right joystick Y
		joystick_value = joystick.joy1_y2;
	}
	if (abs(joystick_value)<5)
	{
		joystick_value=0;
	}
	return (joystick_value);
}

int changerate = 10;

task main ()
{

	waitForStart();

	nMotorEncoder[leftslidemotor]=0;
	/*
	servoChangeRate[leftservo] = changerate; 		//For Ramp Servos
	servoChangeRate[rightservo] = changerate;
	*/
	servoChangeRate[bucketservo] = changerate; 		//For Bucket Servo
	servo[bucketservo] = 128; 						//Set the position of the bucket servo, initially.

	while (true)
	{
		getJoystickSettings(joystick);

			nxtDisplayTextLine (1, "%d",read_joystick (Left));
			nxtDisplayTextLine (2, "%d",read_joystick (Right));
			motor[leftmotor]=(joystick_to_motor (read_joystick (Left)));
			motor[rightmotor]=(joystick_to_motor (read_joystick (Right)));

		/*if (joystick.joy1_TopHat == 4)  // Servos for Ramp (Ramp not currently on Robot, may be added later.)
		{
		servo[rightservo] = 100;
		servo[leftservo] = 100;
		}

		else if (joystick.joy1_TopHat == 0)
		{
		servo[rightservo] = 150;
		servo[leftservo] = 150;
		}

		*/
		if (joy2Btn(5)) 					//If button 8 is pressed move the linear slides down. (Manual control for Linear Slides)
		{
			motor[leftslidemotor]=-50;
			motor[rightslidemotor]=-50;
		}
		else if (joy2Btn(6)) 				//If button 6 is pressed move the linear slides up. (Manual control for Linear Slides)
		{
			motor[leftslidemotor]= 75;
			motor[rightslidemotor]= 75;
		}
		else if (joy2Btn(2)) 				//If button 2 is pressed, move the linear slides down,
		{														//just enough so that they don't hit the lower rung.
			motor[leftslidemotor]=-50;
			motor[rightslidemotor]=-50;
			wait1Msec(100);
			motor[leftslidemotor]=0;
			motor[rightslidemotor]=0;
		}
		else 								//Otherwise stop the motors. (The slides stop when nothing is pressed.)
		{
			motor[leftslidemotor]= 0;
			motor[rightslidemotor]= 0;
		}

		if (joystick.joy2_TopHat == 2) 			//If left d-pad button is pressed, move to the left.
		{
			servo[bucketservo] = 90;
		}
		else if (joystick.joy2_TopHat == 6) 	//If the right d-pad button is pressed, move to the right.
		{
			servo[bucketservo] = 160;
		}
		else 									//If nothing is pressed, move the bucket to the middle.
		{
			servo[bucketservo] = 128;
		}
	}
}
