#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     gyroSensor,     sensorTouch)
#pragma config(Sensor, S4,     IRSensor,       sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     MotorR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     MotorL,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     BotArm,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     TopArm,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Bucket,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "godCode.c"
const int up = 0;
const int down = 1;

void moveBucket(int direction)
{
	if (direction == up)
	{
		motor[Bucket] = -40;
		wait10Msec(30);
		motor[Bucket] = 0;
	}
	else if (direction == down)
	{
		motor[Bucket] = 20;
		wait10Msec(30);
		motor[Bucket] = 0;
	}
}

void arm(int direction)
{
	if (direction == up)
	{
		motor[TopArm] = 50;
		motor[BotArm] = 50;
		wait10Msec(165);
		motor[TopArm] = 0;
		motor[BotArm] = 0;
	}
	else if (direction == down)
	{
		motor[TopArm] = -50;
		motor[BotArm] = -50;
		wait10Msec(165);
		motor[TopArm] = 0;
		motor[BotArm] = 0;
	}
}

void moveToBasket(int motorpower)
{
	rotate(right, motorpower, east);
	drive(motorpower, 8, yes);
	moveBucket(down);
	wait10Msec(100);
	moveBucket(up);
	drive(-(motorpower), 8, yes);
	rotate(left, motorpower, north);
	arm(down);
}

void findIRBasket(int motorpower)
{
	drive(motorpower, 15, yes);
	if (SensorValue[IRSensor] == 8)
	{
		moveToBasket(motorpower);
	}
	wait10Msec(100);
	drive(motorpower, 8, yes);
	if (SensorValue[IRSensor] == 8)
	{
		moveToBasket(motorpower);
	}
	wait10Msec(100);
	drive(motorpower, 8, yes);
	if (SensorValue[IRSensor] == 8)
	{
		moveToBasket(motorpower);
	}
	wait10Msec(100);
	drive(motorpower, 8, yes);
	if (SensorValue[IRSensor] == 8)
	{
		moveToBasket(motorpower);
	}
}

void moveToRamp(int motorpower)
{
	int distanceNeeded = 39 - YCoord;
	drive(motorpower, distanceNeeded + 12, yes);
	rotate(right, motorpower, east);
	drive(motorpower, 16, yes);
	rotate(right, motorpower, south);
	drive(motorpower, 30, yes);
}

task main()
{
	wait10Msec(100);
	StartTask (update_gyroSensor);
	wait10Msec(100);
	arm(up);
	findIRBasket(50);
	//moveToRamp(50);
}
