#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motor2,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
int x = 0;
const int Turn_Time = 1225;
const int Drive_Time = 5500;

// Motors named to be more differentiated
void go_forward(int speed)
{
	motor[motor1] = speed * 0.45;
	motor[motor2] = speed;
}
void go_left(int Left)
{
	motor[motor1] = Left;
	motor[motor2] = x;
}
void go_right(int Right)
{
	motor[motor1] = x;
	motor[motor2] = Right;
}
task main()
{
	// Going forward at full speed
	go_forward(100);
	nxtDisplayCenteredTextLine (3, "Going Forward");
	wait1Msec (Drive_Time);
	// Going left at half speed
	go_left(50);
	nxtDisplayCenteredTextLine (3, "Turning Left");
	wait1Msec (Turn_Time);
	go_forward(100);
	nxtDisplayCenteredTextLine (3, "Going Forward");
	wait1Msec (Drive_Time);
	go_left(50);
	nxtDisplayCenteredTextLine (3, "Turning Left");
	wait1Msec (Turn_Time);
	go_forward(100);
	nxtDisplayCenteredTextLine (3, "Going Forward");
	wait1Msec (Drive_Time);
	go_left(50);
	nxtDisplayCenteredTextLine (3, "Turning Left");
	wait1Msec (Turn_Time);
	go_forward(100);
	nxtDisplayCenteredTextLine (3, "Going Forward");
	wait1Msec (Drive_Time);
	go_left(50);
	nxtDisplayCenteredTextLine (3, "Turning Left");
	wait1Msec (Turn_Time);
	StopAllTasks ();
}
