#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    AGoodName,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
const int SERVO_OPEN=15;
const int SERVO_CLOSE=85;

task main()
{
    //Servo Control for Grabbing Ring
    servoTarget (AGoodName)=SERVO_OPEN;
    while (true)
    {
        getJoystickSettings(joystick);
        if (joy1Btn (2))
        {
            servoTarget (AGoodName)=SERVO_OPEN;
        }
        else if (joy1Btn (4))
        {
            servoTarget (AGoodName)=SERVO_CLOSE;
        }
    }
}
