#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CCustom)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     IRSensor2,      sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     MotorR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     MotorL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     TopArm,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BotArm,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     MidArm,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     Bucket,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////////////////////////////////////////////////////////
//																																									//
//	Green Army Robotics Team 7856 (Tactical Division) 2013-14 Season "Block Party"	//
//	Purpose: To have the robot move on its own for the Autonomous Period						//
//	Contributors: Daniel Herzberg, Aidan O., Warren Li, 														//
//		Mitchell Skaggs, Nathan Skelton, Alex Tariah																	//
//	Last Edited: 10/26/2013																													//
//																																									//
//////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"
#include <hitechnic-gyro.h>

int time = 1;
float RPMs = 0;
float calc = 0;
int iteration = 0;

task secUpdate()
{
	while(true)
	{
		time++;
		wait10Msec(100);
	}
}

task main()
{
	writeDebugStream("\n\n\n\n\n\n\n------------------------------ New Log ------------------------------\n\n");
	StartTask(secUpdate);
	while(true)
	{
		while(iteration <= 7)
		{
			motor[MotorR] = 100 - (10 * iteration);
			wait10Msec(300);
			nMotorEncoder[MotorR] = 0;
			while(time <= 4)
			{
				wait1Msec(1);
			}
			writeDebugStream("The motor power is: %d \n", 100 - (10 * iteration));
			writeDebugStream("The RPMs are: %f \n", (float) nMotorEncoder[MotorR] / 5760);
			writeDebugStream("The voltage of the battery is: %f \n\n", (float)((float)externalBattery / 1000));
			iteration++;
			time = 0;
		}
		iteration = 0;
	}
	motor[MotorR] = 0;
}
