#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     infraredSensor, sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     MotorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     MotorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorBottom,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorTop,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servoGyro,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servoRight,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servoLeft,           tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////////////////////////////////////////////////////////////
//	Green Army Robotics Team 7856 (Tactical Division) 2013-14 Season "Block Party"		//
//	Purpose: To provide control of the Robot during the Tele-Op period					//
//	Contributors: Daniel Herzberg, Aidan O., Warren Li, Mitchell Skaggs, 				//
//		Nathan Skelton, Alex Tariah														//
//	Last Edited: 12/8/2013																//
//////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"

const int  deadzone = 5;
const float max_joy_range = 127.0;
const int   max_motor_range = 100;
const float ratio =  max_motor_range / max_joy_range;
int motorP = 0;

int scale_motor(int joyVal)
{
	if (abs(joyVal) < deadzone)
	{
		return 0;
	}
	else
	{
		motorP = ratio * joyVal;
		return motorP;
	}
}

void joyDrive()
{
	motor[MotorL] = scale_motor(joystick.joy1_y2 + (joystick.joy1_x2)* 2/3);
	motor[MotorR] = scale_motor(joystick.joy1_y2 - (joystick.joy1_x2)* 2/3);
}

void moveConveyer()
{
	if (joy2Btn(6) == true)
	{
		motor[motorBottom] = 25;
	}
	else
	{
		motor[motorBottom] = 0;
	}
	
	if (joy2Btn(8) == true)
	{
		motor[motorTop] = 25;
	}
	else
	{
		motor[motorTop] = 0;
	}
}

void goalGrabber()
{
	if (joy2Btn(1) == true)
	{
		servo[servoRight] = 100;
		servo[servoLeft] = 100;
	}
	else
	{
		servo[servoRight] = 120;
		servo[servoLeft] = 80;
	}
}

void conveyerArm()
{
	if (joy1Btn(1) == true) && 
	{
		motor[motorArm] = scale_motor(joystick.joy1_y2 + (joystick.joy1_x2)* 2/3);
	}
	else
	{
		motor[motorArm] = 0;
	}
}

task main()
{
	waitForStart();
	while(true)
	{
		joyDrive();
		moveConveyer();
		conveyerArm();
		goalGrabber();
	}
}
