#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     infraredSensor, sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     MotorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     MotorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorBottom,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorTop,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servoGyro,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servoRight,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servoLeft,           tServoStandard)
#pragma DebuggerWindows("joystickGame")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////////////////////////////////////////////////////////////
//	Green Army Robotics Team 7856 "The Electronauts" 2014-15 Season "Cascade Effect"		//
//	Purpose: To provide control of the Robot during the Tele-Op period									//
//	Contributors: Daniel Herzberg, Mitchell Skaggs, Nathan Skelton, Alex Tariah					//
//	Last Edited: 11/14/14																																//
//////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"

const int  deadzone = 5;
const float ratio =  100 / 127.0;
int motorP = 0;
bool goalgrabbed = false;

int scale_motor(int joyVal)
{
	if (abs(joyVal) < deadzone)
	{
		return 0;
	}
	else
	{
		motorP = ratio * joyVal;
		return motorP;
	}
}

void joyDrive()
{
	motor[MotorL] = scale_motor(joystick.joy1_y2 + (joystick.joy1_x2));
	motor[MotorR] = scale_motor(joystick.joy1_y2 - (joystick.joy1_x2));
}


// This function is to check for buttons to see if the conveyers should be moved. Later on,
// 	it may be beneficial to turn this into a task and have the buttons be toggles.
void moveConveyer()
{

	// To move bottom conveyer.
	if (joy2Btn(6))
	{
		motor[motorBottom] = 25;
	}
	else
	{
		motor[motorBottom] = 0;
	}

	// To move top conveyer
	if (joy2Btn(8))
	{
		motor[motorTop] = 25;
	}
	else
	{
		motor[motorTop] = 0;
	}
}


// Task to be run for changing the state of the goal grabber arms using an actib
task goalGrabber()
{

	while(true)
	{
		wait1Msec(100);

		if (joy2Btn(1) && goalgrabbed == false)
		{
			// Drop the servos to grab goal
			servo[servoRight] = 100;	// These are test values until proper ones are found
			servo[servoLeft] = 100;
		}
		else
		{
			// Lift servos to release the goal
			servo[servoRight] = 120;
			servo[servoLeft] = 80;
		}

	}
}


// Task to change the state of the conveyer arm. When the button is pressed, the goal will
// 	move up. Along with the move conveyer function, it may be benifical to change this to a
// 	toggle type function for movement up and down.
task conveyerArm()
{
	while(true)
	{
		wait1Msec(100);

		if (joy1Btn(1))
		{
			motor[motorArm] = scale_motor(joystick.joy1_y2 + (joystick.joy1_x2)* 2/3);
		}
		else
		{
			motor[motorArm] = 0;
		}

	}
}

task main()
{

	waitForStart();
	startTask(conveyerArm);
	startTask(goalGrabber);
	while(true)
	{
		joyDrive();
		moveConveyer();
	}
}
