#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     MotorR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     MotorL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     TopArm,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     BotArm,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     BucketMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////////////////////////////////////////////////////////////
//	Green Army Robotics Team 7856 (Tactical Division) 2013-14 Season "Block Party"		//
//	Purpose: To provide control of the Robot during the Tele-Op period					//
//	Contributors: Daniel Herzberg, Aidan O., Warren Li, Mitchell Skaggs, 				//
//		Nathan Skelton, Alex Tariah														//
//	Last Edited: 12/8/2013																//
//////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"

const float a = 5.61630295937;
const float b = 0;
const float c = .157480315;
const float d = 0;
int drivePower = 0;

int cubicRegScale(int joyValue)
{
	drivePower = (a * joyValue * joyValue * joyValue) + (b * joyValue * joyValue) + (c * joyValue) + d;
	return drivePower;
}

void joyDrive()
{
	if (joy1Btn(6) == true)
	{
		motor[MotorL] = cubicRegScale(joystick.joy1_y2 + (joystick.joy1_x2));
		motor[MotorR] = cubicRegScale(joystick.joy1_y2 - (joystick.joy1_x2));
	}
	else
	{
		motor[MotorL] = 0;
		motor[MotorR] = 0;
	}
}

void arm()
{
	if (joy2Btn(5) == true)
	{
		motor[TopArm] = cubicRegScale(joystick.joy2_y1);
		motor[BotArm] = cubicRegScale(joystick.joy2_y1);
	}
	else
	{
		motor[TopArm] = 0;
		motor[BotArm] = 0;
	}
}

void moveBucket()
{
	if (joy2Btn(6) == true)
	{
		motor[BucketMotor] = cubicRegScale(joystick.joy2_y2);
	}
	else
	{
		motor[BucketMotor] = 0;
	}
}

task main()
{
	waitForStart();
	while(true)
	{
		joyDrive();
		arm();
		moveBucket();
	}
}
