#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     infraredSensor, sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     MotorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     MotorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorBottom,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorTop,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servoGyro,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servoRight,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servoLeft,            tServoStandard)
#pragma config(SrvoPosition,  ArmsUp,            128,   0, 128, 128, 175,  15, 128, 129)
#pragma config(SrvoPosition,  ArmsDown,              0,   0, 128, 128,   0, 189, 128, 129)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

////////////////////////////////////////////////////////////////////////////////////////
//																																									  //
//	Pattonville Robotics Team 7856 "The Electronauts" 2014-15 Season "Cascade Effect"	//
//	Purpose: To have the robot move on its own for the Autonomous Period						  //
//	Contributors: Daniel Herzberg, Alex Tariah, Michael Kohler       								  //
//	Last Edited: 10/26/2013																													  //
//																																									  //
////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"
#include <hitechnic-irseeker-v2.h>
#include "C:\Users\7856\Desktop\2014-Code\CommonCode\Autonomous\commonFunctions.c"
#include "hitechnic-gyro.h"

#define conveyorPowerValue 50
bool up = true;
bool down = false;


int rightServoUp = 187;
int rightServoDown = 25;
int leftServoUp = 23;
int leftServoDown = 178;


void drive(int leftPower, int rightPower)
{
	motor[MotorL] = leftPower;
	motor[MotorR] = rightPower;
}


void driveForwardFull()
{
	drive(100,100);
}

int readIR()
{
	int IRValue = SensorValue(infraredSensor);
	return IRValue;
}

void driveForward(int power)
{
	drive(power,power);
}

void driveForwardUntilIR(int power , int IR)
{

}

void driveForwardForTime(int powerValue, int time)
{
	drive(powerValue, powerValue);
	wait1Msec(time);
	drive(0,0);
}

void driveToRampEnd()
{
	moveCmForward(75, 147.32);
}

void turnForTime(int power, int time, int direction)
{
	if(direction == 0)//right
	{
		drive(-power, power);
		wait1Msec(time);
		drive(0,0);
	}
	else if(direction == 1)//left
	{
		drive(power, -power);
		wait1Msec(time);
		drive(0,0);
	}
}


void liftArm()
{
	// motor[conveyorLift] = idk???;
	// wait1Msec(i dont know, we need to figure this out);
}



void lowerArm()
{
	//motor[conveyorLift] = somevalue;
	//wait1Msec(whatever);
}

void setServos(int target)
{
	servo[servoLeft] = target;
	servo[servoRight] = target;
}

//make a turnToAngle function or something
//Down the ramp is 147.32cm
//The distance of the ir sensor from the front is 6.5 inches, the distance from the back is 10.25 in
// top of the ramp is 22 down the ramp is 36 and 17.25 for the length of the robot. IN INCHES
//55.88 91.44 and 43.815

//103.505cm

void setGrabber(bool position)
{
	if(position ==  up)
	{
		servo[servoRight] = 180;
		servo[servoLeft] = 23;
		return;
	}
	else
	{
		servo[servoRight] = 25;
		servo[servoLeft] = 178;
		return;
	}
}

void upArm()
{
	motor[motorArm] = -80;
	wait1Msec(500);
	motor[motorArm] = -50;
	wait1Msec(500);
	motor[motorArm] = 0;
}

void downArm()
{
	motor[motorArm] = 15;
	wait1Msec(650);
	motor[motorArm] = 0;
}

/*
void setGyro(bool position)
{
if(position == up)

}
*/

task main()
{

	downArm();

	waitForStart();


	//driveForwardForTime(40,2000);
	/*
	turnForTime(45,1000,1);
	wait1Msec(1000);
	driveForwardForTime(100,1500);
	drive(0,0);
	turnForTime(45,290,0);
	drive(0,0);
	driveForwardForTime(-100, 500);
	drive(0,0);
	wait1Msec(500);
	driveForwardForTime(100,2000)
	*/
}
