#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S1_C1_1,     rightmotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightslidemotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftmotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftslidemotor, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    bucketservo,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
int joystick_to_motor (int joystick_value) //Converts the joystick value to the motor//
{																					//value using an exponetional function.//
	float motor_value;
	motor_value=(joystick_value*joystick_value/163.4);
	if (joystick_value<0)
	{
		motor_value=motor_value*-1.0;
	}
	return(motor_value);
}
const int Left = 0;
const int Right = 1;

int read_joystick(int side)
{
	int joystick_value;

	// if side is Left
	if (side == Left)
	{
		// read left joystick Y
		joystick_value = joystick.joy1_y1;
	}
	// else
	else if (side == Right)
	{
		// read right joystick Y
		joystick_value = joystick.joy1_y2;
	}
	if (abs(joystick_value)<5)
	{
		joystick_value=0;
	}
	return (joystick_value);
}

bool runCode = true;  //A boolean referenced later that acts as a "kill switch" for the robot.

/*
void moveslidesup(int encodervalue) 		//A void function with the integer encoder value as it's argument,
{											//so that a specified encoder value can be passed to it later.
	//The value is based on measurements developed to get how high each row is in encoder values as units.

	if (nMotorEncoder[leftslidemotor] < encodervalue - 10)			//If the encoder value on the motor is less than the given
	{																//value minus 1, then move up until the value is achieved.
		motor[leftslidemotor]=50;
		motor[rightslidemotor]=50;
		//nxtDisplayTextLine (1, "%d", nMotorEncoder[leftslidemotor]);
	}
	else if (nMotorEncoder[leftslidemotor] > encodervalue + 10)		//If it is greater than the value plus 1, move down until the value
	{																//is achieved.
		motor[leftslidemotor]=-50;
		motor[rightslidemotor]=-50;
		//nxtDisplayTextLine (1, "%d", nMotorEncoder[leftslidemotor]);
	}
	else															//Otherwise, stop moving the motors.
		motor[leftslidemotor]=0;					//The addition and subtraction, gives the slide motors a
		motor[rightslidemotor]=0;					//dead zone to work with.
	//nxtDisplayTextLine (1, "%d", nMotorEncoder[leftslidemotor]);
}

void moveslidesdown()
{
	if (nMotorEncoder[leftslidemotor] > 0) 			//If the encoder value is greater than 0, then move the slides down.
	{
		motor[leftslidemotor]=-100;
		motor[rightslidemotor]=-100;
		//nxtDisplayTextLine (1, "%d", nMotorEncoder[leftslidemotor]);
	}
	else											//If the motor encoder value is zero then stop moving.
	{
		motor[leftslidemotor]=0;
		motor[rightslidemotor]=0;
		//nxtDisplayTextLine (1, "%d", nMotorEncoder[leftslidemotor]);
	}
}

*/
int changerate = 10;



task main ()
{

	waitForStart();

	//bFloatDuringInactiveMotorPWM = false; 		//Sets the motors to break. (Have them stop moving when not given any commands.)
	nMotorEncoder[leftslidemotor]=0;
	/*
	servoChangeRate[leftservo] = changerate; 		//For Ramp Servos
	servoChangeRate[rightservo] = changerate;
	*/
	servoChangeRate[bucketservo] = changerate; 		//For Bucket Servo
	servo[bucketservo] = 128; 						//Set the position of the bucket servo, initially.

	while (true)
	{
		getJoystickSettings(joystick);

		if (runCode == true) 		//If the boolean is true, then run the robot's drive motors.
		{
			nxtDisplayTextLine (1, "%d",read_joystick (Left));
			nxtDisplayTextLine (2, "%d",read_joystick (Right));
			motor[leftmotor]=(joystick_to_motor (read_joystick (Left)));
			motor[rightmotor]=(joystick_to_motor (read_joystick (Right)));
		}
		else 						//Otherwise stop.
		{
			motor[leftmotor]=0;
			motor[rightmotor]=0;
		}
		if (joy1Btn (9)) 			//If button 9 is pressed, kill everything!!!
		{
			runCode = false;
			motor[leftmotor]=0;
			motor[rightmotor]=0;
			motor[leftslidemotor]=0;
			motor[rightslidemotor]=0;
		}
		else if (joy1Btn(10)) 		//If button 10 is pressed, we can have a party again.
		{
			runCode = true;
		}
		/*if (joystick.joy1_TopHat == 4)  // Servos for Ramp (Ramp not currently on Robot, may be added later.)
		{
		servo[rightservo] = 100;
		servo[leftservo] = 100;
		}

		else if (joystick.joy1_TopHat == 0)
		{
		servo[rightservo] = 150;
		servo[leftservo] = 150;
		}

		//WARNING THE CODE BELOW IS EXPERIMENTAL.

		if (joy2Btn (1))			//If joy button 1 is pressed and held, move the slide motors up to place a ring on the first row.
		{
		moveslidesup(2780);
		}

		else if (joy2Btn (2))		//If joy button 2 is pressed and held, move the slide motors up to place a ring on the second row.
		{
		moveslidesup(10015);
		}

		else if (joy2Btn (3))		//If joy button 3 is pressed and held, move the slide motors up to the highest possible!
		{
		moveslidesup(1440);
		}

		else if (joy2Btn (4))		//If joy button 4 is pressed and held, move the slide motors down completely.
		{
		moveslidesdown();
		}

		//WARNING ENDED.
		*/
		else if (joy2Btn(8)) 					//If button 8 is pressed move the linear slides down. (Manual control for Linear Slides)
		{
			motor[leftslidemotor]=-50;
			motor[rightslidemotor]=-50;
		}
		else if (joy2Btn(6)) 				//If button 6 is pressed move the linear slides up. (Manual control for Linear Slides)
		{
			motor[leftslidemotor]= 75;
			motor[rightslidemotor]= 75;
		}
		else 								//Otherwise stop the motors. (The slides also stop when nothing is pressed.)
		{									//Even if joystick 2 button x is being pressed to move the
			motor[leftslidemotor]= 0;		//slides to a specific value, they will stop if that button is released.
			motor[rightslidemotor]= 0;
		}
		if (joy2Btn(9)) 	//If button 9 is pressed, reset the motor encoder value for the left slide motor.
		{									//Only motor with motor encoders.
			nMotorEncoder[leftslidemotor]=0;
		}
		nxtDisplayTextLine (3, "%d", nMotorEncoder[leftslidemotor]); //Always show the value of the left slide motor onscreen.

		if (joystick.joy2_TopHat == 2) 			//If left d-pad button is pressed, move to the left.
		{
			servo[bucketservo] = 100;
		}
		else if (joystick.joy2_TopHat == 6) 	//If the right d-pad button is pressed, move to the right.
		{
			servo[bucketservo] = 140;
		}
		else 									//If nothing is pressed, move the bucket to the middle.
		{
			servo[bucketservo] = 128;
		}
	}
}
