#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     LightSensor,    sensorI2CCustom)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "lego-light.h"

int finalValue = 0;



int findLine()
{
	servo[servo1] = 0;
	int angle = 0;
	int initValue = 0;
	int raw = 0;
	bool isFinished = false;
	int i = 0;
	LSsetActive(LightSensor);
	wait10Msec(100);
	initValue = LSvalNorm(LightSensor);
	nxtDisplayBigTextLine(2, "%d", initValue);
	raw = initValue;
	for(i = 0; abs(raw-initValue)<=4 && i < 255; i++)
	{
		raw = LSvalNorm(LightSensor);
		nxtDisplayBigTextLine(4, "%d", raw);
		if(abs(raw - initValue)> 4)
		{
			isFinished = true;
			finalValue = raw;
		}
		wait10Msec(1);
		servo[servo1] = i;
	}
	angle = i * 180/255;
	int distance = 40*cosDegrees(angle);
	return distance;
};

void turnUntilIRNot(int irValue, int motorSpeed)
{
	while(readIR() == irValue)
	{
     driveStraight (motorSpeed, 0);
	}
}



task main()
{
	findLine();
	eraseDisplay();
	nxtDisplayTextLine(4, "Is Completed");
	wait10Msec(200);
	eraseDisplay();
	nxtDisplayCenteredTextLine(4, "%d", findLine());
	wait10Msec(200);
}
