#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightmotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightslidemotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftmotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftslidemotor, tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


int joystick_to_motor (int joystick_value)
{
	float motor_value;
	motor_value=(joystick_value*joystick_value/163.84);
	if (joystick_value<0)
	{
		motor_value=motor_value*-1.0;
	}
	return(motor_value);
}

const int Left = 0;
const int Right = 1;

int read_joystick(int side)
{
	int joystick_value;


	// if side is Left
	if (side == Left)
	{
		// read left joystick Y
		joystick_value = joystick.joy1_y1;
	}
	// else
	else if (side == Right)
	{

		// read right joystick Y
		joystick_value = joystick.joy1_y2;

	}
	if (abs(joystick_value)<15)
	{
		joystick_value=0;
	}
	return (joystick_value);
}

bool runCode = true;

void moveslidesup(int encodervalue)
{

	if (nMotorEncoder[leftslidemotor] < encodervalue - 1)
	{
		motor[leftslidemotor]=100;
		motor[rightslidemotor]=100;
		nxtDisplayTextLine (1, "%d", nMotorEncoder[leftslidemotor]);
	}
	else if (nMotorEncoder[leftslidemotor] > encodervalue + 1)
	{
		motor[leftslidemotor]=-100;
		motor[rightslidemotor]=-100;
		nxtDisplayTextLine (1, "%d", nMotorEncoder[leftslidemotor]);
	}
	else
		motor[leftslidemotor]=0;
		motor[rightslidemotor]=0;
	nxtDisplayTextLine (1, "%d", nMotorEncoder[leftslidemotor]);
}

void moveslidesdown()
{

	if (nMotorEncoder[leftslidemotor] > 0) //If it is greater than 0 move the slides down.
	{
		motor[leftslidemotor]=-100;
		motor[rightslidemotor]=-100;
		nxtDisplayTextLine (1, "%d", nMotorEncoder[leftslidemotor]);
	}
	else //If the motor encoder value is zero then stop moving.
	{
		motor[leftslidemotor]=0;
		motor[rightslidemotor]=0;
		nxtDisplayTextLine (1, "%d", nMotorEncoder[leftslidemotor]);
	}
}

int changerate = 10;




task main ()
{
	bFloatDuringInactiveMotorPWM = false;
	nMotorEncoder[leftslidemotor]=0;
	/*
	servoChangeRate[leftservo] = changerate;
	servoChangeRate[rightservo] = changerate;
	servoChangeRate[bucketservo] = changerate;
	servo[bucketservo] = 128;

	*/
	while (true)
	{


		getJoystickSettings(joystick);

		if (runCode == true)
		{
			//nxtDisplayTextLine (1, "%d",read_joystick (Left));
			//nxtDisplayTextLine (2, "%d",read_joystick (Right));
			motor[leftmotor]=(joystick_to_motor (read_joystick (Left)));
			motor[rightmotor]=(joystick_to_motor (read_joystick (Right)));
		}
		else
		{
			motor[leftmotor]=0;
			motor[rightmotor]=0;
		}

		if (joy1Btn (9))
		{
			runCode = false;
			motor[leftmotor]=0;
			motor[rightmotor]=0;
			motor[leftslidemotor]=0;
			motor[rightslidemotor]=0;
		}
		else if (joy1Btn(10))
		{
			runCode = true;
		}




		/*
		if (joystick.joy1_TopHat == 4)  // Servos for Ramp
		{
		servo[rightservo] = 100;
		servo[leftservo] = 100;
		}

		else if (joystick.joy1_TopHat == 0)
		{
		servo[rightservo] = 150;
		servo[leftservo] = 150;
		}

		if (joy2Btn (1))
		{
			moveslidesup(360);
		}

		else if (joy2Btn (2))
		{
			moveslidesup(720);
		}

		else if (joy2Btn (3))
		{
			moveslidesup(1440);
		}

		else if (joy2Btn (4))
		{
			moveslidesdown();
		}
		*/
		if (joy2Btn(7))
		{
			motor[leftslidemotor]=-50;
			motor[rightslidemotor]=-50;
		}

		else if (joy2Btn(5))
		{
			motor[leftslidemotor]= 75;
			motor[rightslidemotor]= 75;
		}

		else
		{
			motor[leftslidemotor]= 0;
			motor[rightslidemotor]= 0;
		}
		if (joy2Btn(6))
		{
			nMotorEncoder[leftslidemotor]=0;
		}

		nxtDisplayTextLine (1, "%d", nMotorEncoder[leftslidemotor]);
		/*
		if (joystick.joy1_TopHat == 6)
		{
		servo[bucketservo] = 110;
		}

		else if (joystick.joy1_TopHat == 2)
		{
		servo[bucketservo] = 140;
		}
		else
		{
		servo[bucketservo] = 128;
		}
		*/

	}

}
