#pragma config(Sensor, S1,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          rightmotor,    tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          leftmotor,     tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          armmotor,      tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int distance_in_cm =30;   // Create variable 'distance_in_cm' and initialize it to 20(cm).
	while (true)
	{

		nxtDisplayCenteredTextLine(7, "%d", SensorValue[sonarSensor]);

		if (SensorValue[sonarSensor] > distance_in_cm)   // While the Sonar Sensor readings are less than the specified, 'distance_in_cm':
		{
			motor[motorA] = 35;                     // Motor B is run at a 75 power level
			motor[motorB] = 35;                     // Motor C is run at a 75 power level

		}

		else
		{
			motor[motorA] = 0;
			motor[motorB] = 0;
		}
	}
}
