#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     LEGOLS,         sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     leftmotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightmotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "lego-light.h"





int raw = 0;
const int change = 10;



void driveForLight()
{
	if (raw < 300 && raw > 310)
	{
		motor[leftmotor]=50;
		motor[rightmotor]=35;
		nxtDisplayTextLine(4,"On the Grey");
		nxtDisplayTextLine(7, "Raw:  %4d", raw);
		return;
	}

	else if (raw > 190 && raw < 240)
	{

		motor[leftmotor]=35;
		motor[rightmotor]=35;
		nxtDisplayTextLine(4,"On the black");
		nxtDisplayTextLine(7, "Raw:  %4d", raw);

		return;
	}

	else if (raw > 380 && raw < 450)
	{
		motor[leftmotor]=30;
		motor[rightmotor]=30;
		nxtDisplayTextLine(4,"Lining Up");
		wait1Msec(2000);
		motor[leftmotor]=0;
		motor[rightmotor]=0;
		nxtDisplayTextLine(4, "Lined Up.");
		nxtDisplayTextLine(7, "Raw:  %4d", raw);
	}

	else
	{
		motor[leftmotor]=0;
		motor[rightmotor]=0;
		nxtDisplayTextLine(4,"I can't find the light!");
		nxtDisplayTextLine(7, "Raw:  %4d", raw);
	}

}


task main()
{
	raw = LSvalRaw(LEGOLS);
	LSsetActive(LEGOLS);

	while(true)
	{
		raw = LSvalRaw(LEGOLS);
		driveForLight();
	}
}
