#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(SensorValue(touchSensor) == 0)    // While the Touch Sensor is inactive (hasn't been pressed):
  {
    //motor[motorD] = 100;                        /* Run motors B and C forward */
    //motor[motorE] = 100;                        /* with a power level of 100. */
 		nxtDisplayCenteredTextLine(3,"Not Pressed");
  }
                                          // Otherwise (the touch sensor has been activated [pressed] ):
  //motor[motorD] = -75;                    /* Run motors B and C backwards */
  //motor[motorE] = -75;                    /* with a power level of -75.   */
	nxtDisplayCenteredTextLine(3, "Pressed");
  wait1Msec(1000);                        // Wait 1000 milliseconds (1 second) before moving to further code.
}
