#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CCustom)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     IRSensor2,      sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     MotorR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     MotorL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     TopArm,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BotArm,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    Bucket,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////
////																					////
////	Green Army Robotics Team 7856 (Tactical Division) 2013-14 Season "Block Party"	////
////	Purpose: To have the robot move on its own for the Autonomous Period			////
////	Contributors: Daniel Herzberg, Aidan O., Warren Li, 							////
////		Mitchell Skaggs, Nathan Skelton, Alex Tariah								////
////	Last Edited: 10/26/2013															////
////																					////
////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"
#include <hitechnic-gyro.h>
// Joystick drivers

const int left = 0;
const int right = 1;
const int forward = 2;
const int backward = 3;
const int gyro_on_ramp = 0;

int ir2_value = SensorValue[IRSensor2];

task update_IRsensor()
{
	ir2_value = SensorValue[IRSensor2];
}

float happy_angle=0;

task update_gyroSensor()
{
	HTGYROstartCal(gyroSensor);
	while(true)
	{
		float angle=HTGYROreadRot(gyroSensor) / 100.0;
		happy_angle=happy_angle+angle;
		nxtDisplayTextLine(7, "%d", happy_angle);
		wait1Msec (10);
	}
}

void move(int direction, int motorspeed, int time)
{
	if (direction == backward)
	{
		motor[MotorL] = - motorspeed;
		motor[MotorR] = - motorspeed;
		nxtDisplayTextLine(1,"Moving Backward");
		wait1Msec(time);
	}
	else if (direction == forward)
	{
		motor[MotorL] = motorspeed;
		motor[MotorR] = motorspeed;
		nxtDisplayTextLine(1,"Moving Forward");
		wait1Msec(time);
	}
	else if (direction == left)
	{
		motor[MotorL] = - motorspeed;
		motor[MotorR] = motorspeed;
		nxtDisplayTextLine(1,"Rotating Left");
		wait1Msec(time);
	}
	else if (direction == right)
	{
		motor[MotorL] = motorspeed;
		motor[MotorR] = - motorspeed;
		nxtDisplayTextLine(1,"Rotating Right");
		wait1Msec(time);
	}
	else
	{
		nxtDisplayTextLine(1,"Stoping");
		motor[MotorL] = 0;
		motor[MotorR] = 0;
	}
}

void stop_drive()
{
	nxtDisplayTextLine(1,"Stoping");
	motor[MotorL] = 0;
	motor[MotorR] = 0;
}

void drive_on_ramp(int motorspeed)
{
	nxtDisplayTextLine(2,"Finding Ramp");
	while (happy_angle < gyro_on_ramp)
	{
		move(forward, motorspeed, 0);
	}
	nxtDisplayTextLine(2,"Stoping On Ramp");
	stop_drive();
}

void find_ir_basket(int motorspeed, int time)
{
	while ( ir2_value != 2 && ir2_value != 8)
	{
		move(forward, motorspeed, 0);
	}
	if (ir2_value == 2)
	{
		move(left, motorspeed, time);
	}
	else if (ir2_value == 8)
	{
		move(right, motorspeed, time);
	}
	else
	{
		stop_drive();
	}
}

task main()
{
	StartTask(update_gyroSensor);
	find_ir_basket(75, 0);

}
