#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     LIGHTSENSEI,    sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     Motorleft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Motorright,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>

void driveUntil()
{
	if(SensorValue[S2] >= 30)
	{
		motor[Motorleft] = 0;
		motor[Motorright] = 0;
	}
	else
	{
		motor[Motorleft] = 40;
		motor[Motorright] = 40;
	}
};

task main()
{
	disableDiagnosticsDisplay();
	while(true)
	{
		driveUntil();
	}
}
