#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     irseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Sensor, S4,     lineSensor,     sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     Motorleft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Motorright,    tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>
#include <hitechnic-irseeker-v2.h>

int readIR()
{
	int IRValue = HTIRS2readACDir(irseeker);
	return IRValue;
}

bool alignWithBeacon = false;

void followIR()
{
	if (readIR()< 5 && readIR()>0)
	{
		motor[Motorleft]=-50;
		motor[Motorright]=50;
		nxtDisplayTextLine(3,"Left");
	}
	else if (readIR()> 5)
	{
		motor[Motorleft]=50;
		motor[Motorright]=-50;
		nxtDisplayTextLine(3,"Right");
	}
	else if (readIR()== 5)
	{
		motor[Motorleft]=25;
		motor[Motorright]=25;

		nxtDisplayTextLine(3,"Forward");
	}
	else
	{
		motor[Motorleft]=0;
		motor[Motorright]=0;

		nxtDisplayTextLine(3,"Stop");
	}
}

bool isOnLine()
{
	if(SensorValue[lineSensor] > 45)
	{
		return true;
	}
	else
	{
		return false;
	}

}

bool bumperIsPressed()
{
	if(SensorValue(touchSensor) == 1)
	{
		return true;
	}
	else
	{
		return false;
	}
}

bool inLineWithGoal()
{
	if(isOnLine() == true && SensorValue[irseeker] == 4)
	{
		return true;
	}
	else
	{
		return false;
	}
}

int alignWithBeaconPole()
{

}



task main()
{

	while(true)
	{
		//Drive Forward, while the IR receiver reads a value of 5
		//
		if(SensorValue(irseeker) == 5 && bumperIsPressed() == false)
		{
			motor[Motorright] = 35;
			motor[Motorleft] = 35;
		}
		else if(SensorValue(irseeker) == 0 && bumperIsPressed() == false)
		{
			motor[Motorright] = -5;
			motor[Motorleft] = -5;
		}
		else
		{
			motor[Motorright] = 0;
			motor[Motorleft] = 0;
		}
	}
}
